modLoader = "javafml" #mandatory
loaderVersion = "${forgeLoaderVersion}"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/ManasMods/ManasCore/issues" #optional
[[mods]] #mandatory
modId = "${modId}" #mandatory
version = "${modVersion}"
displayName = "ManasCore" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="https://github.com/ManasMods/ManasCore/wiki" #optional
#logoFile="ManasCore.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "ManasMods" #optional
description = '''
Utility and Core Library for Manas Mods
'''
#@formatter:off
[[dependencies.ManasCore]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="${forgeLoaderVersion}" #mandatory
   ordering="NONE"
   side="BOTH"
# Here's another dependency
[[dependencies.ManasCore]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="${minecraftVersionCheck}"
   ordering="NONE"
   side="BOTH"
##@formatter:on