name: Publish to CurseForge

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Set Gradle Permissions
        run: chmod +x gradlew
      - name: install git
        run: sudo apt-get install git -y
      - name: Build Mod
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
      - name: Generate Changelog
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: makeChangelog
      - name: Publish to CurseForge
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: curseforge
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
